AllCops:
  Excludes:
    - bin/*
    - config/**
    - coverage/**
    - db/**
    - doc/**
    - log/**
    - public/**
    - script/**
    - tmp/**
    - vendor/**
  RunRailsCops: true

MethodCalledOnDoEndBlock:
  Enabled: true

Documentation:
  Exclude:
    - app/api/**
    - app/controllers/**
    - app/helpers/**
