language: ruby
cache: bundler
rvm:
  - 2.2.2
addons:
  postgresql: '9.3'
env:
  - DB_USER=postgres
    RAILS_ENV=test
before_script:
  - psql -U postgres -c 'CREATE DATABASE orodruin_test;'
  - cp config/database.yml.travis config/database.yml
  - bin/rake db:setup
services:
  - redis-server
script:
  bin/rake test:ci
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f3e7ceaf2c1d5e25b989
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
git:
  depth: 10
