language: ruby
rvm:
  - 2.1.2
addons:
  postgresql: '9.3'
env:
  - DB_USER=postgres
before_script:
  - psql -U postgres -c 'CREATE DATABASE orodruin_test;'
script:
  bin/rake test:ci
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a2a40dc92d4a0ebd1e2a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
git:
  depth: 10
