web:
  build: .
  volumes:
    - ".:/usr/src/app"
  environment:
    DATABASE_URL: postgresql://postgres@db/
  command: unicorn -c config/unicorn.rb -p 5000
  ports:
    - 5000:5000
  links:
    - db
    - redis

worker:
  build: .
  volumes:
    - ".:/usr/src/app"
  environment:
    DATABASE_URL: postgresql://postgres@db/
  command: sidekiq -C config/sidekiq.yml
  links:
    - db
    - redis

db:
  image: postgres:9.4

redis:
  image: redis:2
