app:
  build: .
  volumes:
    - ".:/app"
  environment:
    DATABASE_URL: postgresql://postgres@db/

web:
  extends:
    file: docker-compose.yml
    service: app
  command: unicorn -c config/unicorn.rb -p 5000
  ports:
    - 5000:5000
  links:
    - db
    - redis

worker:
  extends:
    file: docker-compose.yml
    service: app
  command: sidekiq -C config/sidekiq.yml
  links:
    - db
    - redis

db:
  image: postgres:9.4

redis:
  image: redis:2
